//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuteshestvuiPoRossii.AppData
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.Hotel = new HashSet<Hotel>();
            this.Type = new HashSet<Type>();
        }
    
        public int Id { get; set; }
        public int TicketCount { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] ImagePreview { get; set; }
        public decimal Price { get; set; }
        public bool IsActual { get; set; }

        public string Status
        {
            get
            {
                if (IsActual == true)
                    return "Актуален";
                else
                    return "Не актуален";
            }
        }

        public string FullTicketCount
        {
            get
            {
                return "Билетов: " + TicketCount;
            }
        }

        public SolidColorBrush colorBrush
        {
            get
            {
                if (IsActual == true)
                    return Brushes.Green;
                else
                    return Brushes.Red;
            }
        }
        public string FullPriceView
        {
            get
            {
                return Price + "руб.";
            }
        }

        public string ImgPath
        {
            get
            {
                return "/Resources/" + Name + ".jpg";
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel> Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Type> Type { get; set; }
    }
}
